package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

// ConfigSource indica a origem de um valor de configuração.
type ConfigSource string

const (
	SourceCLIFlag          ConfigSource = "CLI flag"
	SourceConfigFile       ConfigSource = "config.toml"
	SourceEnvVar           ConfigSource = "env var"
	SourceGeneratedDefault ConfigSource = "generated default"
	SourceHardcodedDefault ConfigSource = "hardcoded default"
)

// ResolvedConfig contém a configuração final + metadata de resolução.
type ResolvedConfig struct {
	Config   *Config
	Sources  map[string]ConfigSource // campo → origem
	Warnings []string
}

// ResolveOptions são os overrides passados via CLI flags.
type ResolveOptions struct {
	ConfigPath   string // --config
	Bind         string // --bind
	AdminAPIKey  string // --admin-api-key
	VPNProvider  string // --vpn-provider
	DBPath       string // --db-path
	LogLevel     string // --log-level
	LogFormat    string // --log-format
	GenerateOnly bool   // --generate-config (gerar e sair)
	ValidateOnly bool   // --validate-config (validar e sair)
}

// Resolve aplica a cascata de prioridade e retorna a config final.
func Resolve(opts ResolveOptions) (*ResolvedConfig, error) {
	sources := make(map[string]ConfigSource)
	var warnings []string

	// ── Passo 1: Carregar base do config.toml ou auto-gerar ─────────────
	configPath := opts.ConfigPath
	if configPath == "" {
		configPath = DefaultConfigPath()
	}

	var cfg *Config
	autoGenerated := false

	if _, err := os.Stat(configPath); err == nil {
		cfg = Defaults()
		data, readErr := os.ReadFile(configPath)
		if readErr != nil {
			return nil, fmt.Errorf("failed to read config at %s: %w", configPath, readErr)
		}
		if parseErr := toml.Unmarshal(data, cfg); parseErr != nil {
			return nil, fmt.Errorf("failed to parse config at %s: %w", configPath, parseErr)
		}
		slog.Info("📄 Loaded config", "path", configPath)
		markAllFieldsAsSource(sources, SourceConfigFile)
	} else {
		slog.Warn("🔧 First-time setup: config not found. Generating...", "path", configPath)
		cfg = Defaults()
		autoGenerated = true
		markAllFieldsAsSource(sources, SourceHardcodedDefault)
	}

	// ── Passo 2: Env vars (deprecated) — só se NÃO foi auto-gerado ──────
	if !autoGenerated {
		applyEnvOverridesWithSources(cfg, sources, &warnings)
	}

	// ── Passo 3: CLI flags (mais alta prioridade) ───────────────────────
	applyCLIOverrides(cfg, opts, sources)

	// ── Passo 4: Auto-generate admin key se vazia ───────────────────────
	if strings.TrimSpace(cfg.Auth.AdminAPIKey) == "" {
		generated := generateAdminKey()
		cfg.Auth.AdminAPIKey = generated
		sources["auth.admin_api_key"] = SourceGeneratedDefault
		slog.Warn("🔑 Generated admin API key (first run)", "key_preview", maskSecret(generated))
		warnings = append(warnings, fmt.Sprintf(
			"Auto-generated admin_api_key: %s", maskSecret(generated),
		))
	}

	// ── Passo 5: Se auto-gerado, escrever config.toml no disco ──────────
	if autoGenerated {
		if err := WriteConfig(configPath, cfg); err != nil {
			return nil, fmt.Errorf("failed to write auto-generated config: %w", err)
		}
		slog.Info("💾 Auto-generated config saved", "path", configPath)
		warnings = append(warnings, fmt.Sprintf(
			"Auto-generated config at %s. Edit manually or re-run with flags.", configPath,
		))
	}

	// ── Passo 6: Validar ────────────────────────────────────────────────
	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("invalid configuration: %w", err)
	}

	// ── Passo 7: Log de transparência ──────────────────────────────────
	logResolvedConfig(cfg, sources)

	return &ResolvedConfig{
		Config:   cfg,
		Sources:  sources,
		Warnings: warnings,
	}, nil
}

var resolverEnvMappings = []struct {
	envVar  string
	field   string
	cliFlag string
	apply   func(cfg *Config, value string)
}{
	{"COORD_BIND", "server.bind", "--bind", func(c *Config, v string) { c.Server.Bind = v; c.Server.Listen = v }},
	{"COORD_LISTEN", "server.bind", "--bind", func(c *Config, v string) { c.Server.Bind = v; c.Server.Listen = v }},
	{"COORD_ADMIN_API_KEY", "auth.admin_api_key", "--admin-api-key", func(c *Config, v string) { c.Auth.AdminAPIKey = v }},
	{"COORD_DB_PATH", "database.path", "--db-path", func(c *Config, v string) { c.Database.Path = v }},
	{"COORD_VPN_PROVIDER", "vpn.provider", "--vpn-provider", func(c *Config, v string) { c.VPN.Provider = v }},
	{"COORD_TAILSCALE_API_KEY", "vpn.tailscale_api_key", "(none)", func(c *Config, v string) { c.VPN.TailscaleAPIKey = v }},
	{"COORD_HEADSCALE_URL", "vpn.headscale_url", "(none)", func(c *Config, v string) { c.VPN.HeadscaleURL = v; c.VPN.HeadscaleAPIURL = v }},
	{"COORD_LOG_LEVEL", "log.level", "--log-level", func(c *Config, v string) { c.Log.Level = v }},
	{"COORD_LOG_FORMAT", "log.format", "--log-format", func(c *Config, v string) { c.Log.Format = v }},
}

func applyEnvOverridesWithSources(cfg *Config, sources map[string]ConfigSource, warnings *[]string) {
	configPath := DefaultConfigPath()
	for _, m := range resolverEnvMappings {
		value, ok := os.LookupEnv(m.envVar)
		if !ok || strings.TrimSpace(value) == "" {
			continue
		}

		parts := strings.Split(m.field, ".")
		section := parts[0]
		key := parts[0]
		if len(parts) > 1 {
			key = parts[1]
		}

		warning := fmt.Sprintf(
			"⚠️  DEPRECATED: %s=%s\n"+
				"   This env var will be removed in v0.3.0.\n"+
				"   Migrate now:  edit %s → [%s] %s\n"+
				"   Or use flag:  %s %s",
			m.envVar, maskSecret(value),
			configPath, section, key,
			m.cliFlag, value,
		)
		slog.Warn(warning)
		*warnings = append(*warnings, warning)

		// Env vars só sobrescrevem defaults, não config.toml
		if sources[m.field] == SourceHardcodedDefault || sources[m.field] == "" {
			m.apply(cfg, value)
			sources[m.field] = SourceEnvVar
		}
	}
}

func applyCLIOverrides(cfg *Config, opts ResolveOptions, sources map[string]ConfigSource) {
	if opts.Bind != "" {
		cfg.Server.Bind = opts.Bind
		cfg.Server.Listen = opts.Bind
		sources["server.bind"] = SourceCLIFlag
	}
	if opts.AdminAPIKey != "" {
		cfg.Auth.AdminAPIKey = opts.AdminAPIKey
		sources["auth.admin_api_key"] = SourceCLIFlag
	}
	if opts.VPNProvider != "" {
		cfg.VPN.Provider = opts.VPNProvider
		sources["vpn.provider"] = SourceCLIFlag
	}
	if opts.DBPath != "" {
		cfg.Database.Path = opts.DBPath
		sources["database.path"] = SourceCLIFlag
	}
	if opts.LogLevel != "" {
		cfg.Log.Level = opts.LogLevel
		sources["log.level"] = SourceCLIFlag
	}
	if opts.LogFormat != "" {
		cfg.Log.Format = opts.LogFormat
		sources["log.format"] = SourceCLIFlag
	}
}

func generateAdminKey() string {
	b := make([]byte, 32)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func maskSecret(s string) string {
	if len(s) <= 4 {
		return "****"
	}
	return s[:4] + "****"
}

func markAllFieldsAsSource(sources map[string]ConfigSource, source ConfigSource) {
	fields := []string{
		"server.bind", "auth.admin_api_key", "database.path",
		"vpn.provider", "vpn.tailscale_api_key", "vpn.tailscale_tailnet",
		"vpn.headscale_url", "vpn.headscale_api_key", "vpn.headscale_user",
		"vpn.key_expiry_hours", "ratelimit.requests_per_minute",
		"log.level", "log.format",
	}
	for _, f := range fields {
		sources[f] = source
	}
}

func logResolvedConfig(cfg *Config, sources map[string]ConfigSource) {
	slog.Info("═══ Resolved Configuration ═══")

	fields := []struct {
		name  string
		value string
	}{
		{"server.bind", cfg.Server.Bind},
		{"auth.admin_api_key", maskSecret(cfg.Auth.AdminAPIKey)},
		{"database.path", cfg.Database.Path},
		{"vpn.provider", cfg.VPN.Provider},
		{"ratelimit.requests_per_minute", fmt.Sprintf("%d", cfg.RateLimit.RequestsPerMinute)},
		{"log.level", cfg.Log.Level},
		{"log.format", cfg.Log.Format},
	}

	for _, f := range fields {
		source := sources[f.name]
		if source == "" {
			source = "implicit default"
		}
		slog.Info(fmt.Sprintf("  %s = \"%s\" ← %s", f.name, f.value, source))
	}

	slog.Info("═══════════════════════════════")
}
